import { dirname } from "node:path";
import { fileURLToPath } from "node:url";

import { FlatCompat } from "@eslint/eslintrc";

/**
 * eslint-config-next 15 still ships eslintrc-style configs only, so ESLint 9's
 * flat config has to bridge to them through FlatCompat. Importing the config
 * directly makes the rushstack patch fail with
 * "Failed to patch ESLint because the calling module was not recognized".
 */
const compat = new FlatCompat({ baseDirectory: dirname(fileURLToPath(import.meta.url)) });

const config = [
  // next-env.d.ts is generated by Next on every build; it is not ours to lint.
  // qa/ holds throwaway Playwright drivers run with plain node, not bundled.
  { ignores: [".next/**", "node_modules/**", "public/**", "scripts/**", "qa/**", "next-env.d.ts"] },
  ...compat.extends("next/core-web-vitals", "next/typescript"),
];

export default config;
