/**
 * Generates public/robots.txt, public/sitemap.xml and public/manifest.webmanifest
 * from lib/site.config.ts. Runs automatically via the `prebuild` npm script.
 *
 * WHY THIS EXISTS RATHER THAN app/robots.ts
 * -----------------------------------------
 * Next can generate all three natively from app/robots.ts, app/sitemap.ts and
 * app/manifest.ts, and on a normally-named folder that is what you should use.
 * Next's metadata-route loader pastes the file's absolute path into a
 * single-quoted JavaScript string without escaping it, so a project folder
 * containing an apostrophe produces a generated module that will not parse.
 * This project's folder is fine today, but the site is meant to be moved and
 * deployed by people who did not read this comment, and generating the three
 * files from the same config costs nothing and cannot break.
 *
 * Everything below still comes from site.config.ts, so nothing is maintained
 * twice. It also shouts about the placeholders that must be replaced before
 * launch, because a build log is the last place they can be caught for free.
 */

import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { SITE, SITE_URL } from "../lib/site.config.ts";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const publicDir = join(root, "public");

const ROUTES = ["/", "/privacy", "/cookies", "/terms", "/credits"];
const today = new Date().toISOString().slice(0, 10);

const robots = `# ${SITE.business.name} — ${SITE.business.tagline}
# Generated by scripts/generate-meta.mjs - do not edit by hand.

User-agent: *
Allow: /

Sitemap: ${SITE_URL}/sitemap.xml
`;

const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/generate-meta.mjs - do not edit by hand. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${ROUTES.map(
  (route) => `  <url>
    <loc>${SITE_URL}${route}</loc>
    <lastmod>${today}</lastmod>
    <changefreq>${route === "/" ? "weekly" : "yearly"}</changefreq>
    <priority>${route === "/" ? "1.0" : "0.2"}</priority>
  </url>`,
).join("\n")}
</urlset>
`;

const manifest = {
  name: `${SITE.business.name} — ${SITE.business.tagline}`,
  short_name: "Chuckles & Chai",
  description:
    "Evening chai café. Slow-boiled masala chai, degree filter kaapi and food worth staying for.",
  lang: "en-IN",
  start_url: "/",
  scope: "/",
  display: "standalone",
  orientation: "portrait",
  background_color: "#FBF8F2",
  theme_color: "#6E1F2E",
  categories: ["food", "lifestyle"],
  icons: [
    { src: "/favicon.svg", sizes: "any", type: "image/svg+xml", purpose: "any" },
    { src: "/images/apple-touch-icon.png", sizes: "180x180", type: "image/png", purpose: "maskable" },
  ],
};

await mkdir(publicDir, { recursive: true });
await Promise.all([
  writeFile(join(publicDir, "robots.txt"), robots, "utf8"),
  writeFile(join(publicDir, "sitemap.xml"), sitemap, "utf8"),
  writeFile(join(publicDir, "manifest.webmanifest"), `${JSON.stringify(manifest, null, 2)}\n`, "utf8"),
]);

console.log("generate-meta: wrote robots.txt, sitemap.xml, manifest.webmanifest");

/* == PRE-LAUNCH CHECK ======================================================
   Nothing here fails the build - a placeholder address should not stop a
   preview deploy - but it must not be possible to ship without being told. */
const b = SITE.business;
const outstanding = [];
if (b.street.startsWith("Shop address")) outstanding.push("business address (street / area / city / state / postcode)");
if (b.phoneLink.replace(/\D/g, "").replace(/^91/, "").replace(/0+/g, "") === "") outstanding.push("phone number");
if (!b.lat || !b.lng) outstanding.push("map coordinates (lat / lng)");
if (SITE.ordering.enabled && /^910*$/.test(SITE.ordering.whatsapp ?? "")) outstanding.push("WhatsApp number for order-ahead");
if (SITE_URL.includes("chucklesandchai.in")) outstanding.push("NEXT_PUBLIC_SITE_URL (canonical domain)");

if (outstanding.length) {
  console.log("\n  !! STILL A PLACEHOLDER IN lib/site.config.ts:");
  for (const item of outstanding) console.log(`     - ${item}`);
  console.log("     See README.md, 'Before launch'.\n");
}
